[project]
name = "rag-core"
version = "0.1.0"
description = "Shared OpenAI retrieval helpers for LiveKit multi-agent services"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.0.0",
]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
