[project]
name = "rag-core"
version = "0.1.0"
description = "Shared PDF RAG components for LiveKit multi-agent services"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.12.0",
    "langdetect>=1.0.9",
    "numpy>=2.3.4",
    "openai>=1.0.0",
    "pypdf>=6.1.2",
    "requests>=2.32.5",
    "sentence-transformers>=5.1.1",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
